In [6]:
import numpy as np


In [10]:
a = np.array([1,2,3])
a

array([1, 2, 3])

In [11]:
print(np.__version__)

1.18.1


In [12]:
b= np.array([1,2,3,4,5])
type(b)

numpy.ndarray

In [13]:
type(a)

numpy.ndarray

In [21]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
arr

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]])

In [23]:
import numpy as np

arr = np.array([1, 2, 3, 4])

print(arr)
print('number of dimensions :', arr.ndim)

[1 2 3 4]
number of dimensions : 1


In [26]:
arr = np.array([1, 2, 3, 1])
arr[0] == arr[3]

True

In [29]:
arr = np.array([1, 2, 3, 4.])
print(arr.dtype)

float64


In [43]:
from numpy import random
arr = random.randint(1,30,(3,3))
arr

array([[27, 11,  9],
       [11, 13,  9],
       [21, 22,  7]])

In [44]:
## Write a Python program to create an array of 5 integers and display the array items. Access individual element through indexes.

In [71]:
arr = np.random.randint(1,10,5)
print(arr[0])
print(arr[1])    
print(arr[2])

4
3
2


In [72]:
## Write a Python program to append a new item to the end of the array

In [ ]:
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([6])
arr = np.concatenate((arr1, arr2))
arr


In [ ]:
## Write a Python program to reverse the order of the items in the array

In [100]:
arr = np.array([1,2,3,43,5,34])
res = arr[::-1]
res

array([34,  5, 43,  3,  2,  1])

In [116]:
##Write a Python program to get the length in bytes of one array item in the internal representation

In [115]:
str = "Geeksforgeeks"
  
# encoding the string with unicode 8 and 16 
array1 = bytearray(str, 'utf-8') 
array2 = bytearray(str, 'utf-16') 
  
print(len(array1))
print((len(array2))) 

13
28


In [113]:
# simple list of integers 
list = [1, 3, 5, 7, 9] 
  
# iterable as source 
array = bytearray(list) 
  
print(array) 
print("Count of bytes:", len(array)) 

bytearray(b'\x01\x03\x05\x07\t')
Count of bytes: 5


In [ ]:
##Write a Python program to get the number of occurrences of a specified element in an array.

In [133]:
arr = [1,2,3,4,5,6,7,1,23,1,1]
a = []
for i in arr:
    a = arr.count(i)
    print('element', i , 'count' , a)

element 1 count 4
element 2 count 1
element 3 count 1
element 4 count 1
element 5 count 1
element 6 count 1
element 7 count 1
element 1 count 4
element 23 count 1
element 1 count 4
element 1 count 4


In [ ]:
##Write a Python program to append items from inerrable to the end of the array

In [142]:
arr1 = np.random.randint(1,10,7)
new_arr = np.concatenate((arr1,arr1))
new_arr

array([8, 3, 8, 2, 5, 8, 7, 8, 3, 8, 2, 5, 8, 7])

In [ ]:
##Write a Python program to convert an array to an array of machine values and return the bytes representation

In [149]:
from array import *
print("Bytes to String: ")
x = array('b', [119, 54, 114, 101,  115, 111, 117, 114, 99, 101])
s = x.tobytes()
print(s)


Bytes to String: 
b'w6resource'


In [ ]:
##Write a Python program to append items from a specified list.

In [157]:
list1 = [1,2,3,4]
arr = np.array(list1)
arr

array([1, 2, 3, 4])

In [ ]:
## Write a Python program to insert a new item before the second element in an existing array.

In [165]:
arr = np.array([1,2,3,4,5,6])
X = np.insert(arr, 1, 10, axis=0)
X

array([ 1, 10,  2,  3,  4,  5,  6])