In [1]:
import numpy as np

In [2]:
## Write a Python program to remove a specified item using the index from an array.

In [4]:
arr = np.array([1,2,3,4,5,6,7])
new_arr = np.delete(arr,[0,3,5])
new_arr

array([2, 3, 5, 7])

In [5]:
arr = np.array([1,2,3,4,5,6,7])
new_arr = np.delete(arr,[4])
new_arr

array([1, 2, 3, 4, 6, 7])

In [ ]:
##Write a Python program to remove the first occurrence of a specified element from an array.

In [6]:
arr = np.array([10,112,230,234,2414,10])
new_arr = np.delete(arr, np.where(arr == 10))
new_arr

array([ 112,  230,  234, 2414])

In [ ]:
##Write a Python program to convert an array to an ordinary list with the same items

In [7]:
arr = np.array([10,112,230,234,2414,10])
list= arr.tolist()
list

[10, 112, 230, 234, 2414, 10]

In [ ]:
## Write a Python program to find whether a given array of integers contains any duplicate element. Return true if any value appears at least twice in the said array and return false if every element is distinct.

In [31]:
def test_duplicate(array_nums):
    nums_set = set(array_nums)    
    return len(array_nums) != len(nums_set)

print(test_duplicate([1,2,3,4,5,6,7,1,23,3]))
print(test_duplicate([1,2,3,4,5,6,7]))

True
False


In [32]:
##Write a Python program to find the first duplicate element in a given array of integers. Return -1 If there are no such elements.

In [41]:
def find_first_duplicate(arr):
    num_set = set()
    no_duplicate = -1

    for i in range(len(arr)):

        if arr[i] in num_set:
            return arr[i]
        else:
            num_set.add(arr[i])

    return no_duplicate

print(find_first_duplicate([1, 2, 3, 4, 4, 5]))
print(find_first_duplicate([1, 2, 3, 4]))
print(find_first_duplicate([1, 1, 2, 3, 3, 2, 2]))


4
-1
1
